import { MAPS_COUNT } from '../config/consts';

require('../assets/platform/platform.png');
require('../assets/enemy/enemy.png');
require('../assets/item/item.png');
require('../assets/item/flag.png');
require('../assets/character/character.png');
require('../assets/background/forest_morning.png');
require('../assets/background/forest_afternoon.png');
require('../assets/background/forest_evening.png');
require('../assets/background/forest_noon.png');
require('../assets/background/failure.png');
require('../assets/background/success.png');
require('../assets/title/title.png');
require('../assets/status/0.png');
require('../assets/status/1.png');
require('../assets/status/2.png');
require('../assets/status/3.png');
require('../assets/status/4.png');
require('../assets/status/5.png');
require('../assets/status/6.png');
require('../assets/status/7.png');
require('../assets/status/8.png');
require('../assets/status/9.png');
require('../assets/status/dot.png');
require('../assets/status/clock.png');
require('../assets/status/gold.png');
require('../assets/status/bronze.png');
require('../assets/status/heartEmpty.png');
require('../assets/status/heartFull.png');
require('../assets/audio/bgm.mp3');
require('../assets/audio/getItem.mp3');
require('../assets/audio/bounce.mp3');
require('../assets/audio/injured.mp3');
require('../assets/audio/jump.mp3');
require('../assets/audio/killEnemy.mp3');
[...new Array(MAPS_COUNT)].map((i, j) => require(`../assets/map/${j + 1}.json`));
